"""
Pydantic Task Documents for DMAx jobs.

"""
from pydantic import BaseModel, Field
from typing import Optional, Any, Dict, List


class DmaxStructureTaskDocument(BaseModel):
    """Task document for polymer structure generation."""

    packmol_pdb: Optional[str] = Field(
        None, description="Contents of the packmol PDB file"
    )
    polymer_pdb: Optional[str] = Field(
        None, description="Contents of the generated polymer PDB file"
    )
    builder_wrapper: Optional[Any] = Field(
        None, description="Serialized PSPBuilderWrapper for reuse"
    )


class DmaxForceFieldTaskDocument(BaseModel):
    """Task document for force‑field parametrization."""

    data_file: str = Field(..., description="Path or name of the generated LAMMPS data file")
    lammps_data: Optional[str] = Field(
        None, description="Contents of the generated LAMMPS data file"
    )
    forcefield_type: str = Field(..., description="Type of forcefield used ('opls' or 'gaff2')")


class DmaxDataGenerationFlowDocument(BaseModel):
    """Document for the complete DMAx data‑generation flow."""

    packmol_pdb: Optional[Any] = Field(None, description="Reference or contents of the packmol PDB file")
    polymer_pdb: Optional[Any] = Field(None, description="Reference or contents of the generated polymer PDB file")
    data_file: Any = Field(..., description="Path to the generated LAMMPS data file")
    lammps_data: Optional[Any] = Field(None, description="Reference or contents of the generated LAMMPS data file")


class DmaxLammpsInputDocument(BaseModel):
    """Task document for generated LAMMPS input files."""

    input_dir: str = Field(..., description="Directory containing generated LAMMPS input and slurm files")
    data_file: str = Field(..., description="Filename of the LAMMPS data file in the input directory")
    input_file: str = Field(..., description="Filename of the LAMMPS input script generated from template")
    slurm_file: str = Field(..., description="Filename of the SLURM run script in the input directory")


class DmaxLammpsRunDocument(BaseModel):
    """Task document for a submitted LAMMPS SLURM run."""

    job_id: str = Field(..., description="SLURM job ID for the LAMMPS run or 'local'")
    restart_file: Optional[str] = Field(None, description="Path to the restart.equil file generated by LAMMPS")


class DmaxStructureEquilibrationFlowDocument(BaseModel):
    """Document for the complete structure‑equilibration flow."""

    packmol_pdb: Optional[Any] = Field(None, description="Contents of the packmol PDB file for the polymer structure")
    polymer_pdb: Optional[Any] = Field(None, description="Contents of the generated polymer PDB file")
    lammps_data: Optional[Any] = Field(None, description="Contents of the LAMMPS data file")
    lammps_input: Optional[Any] = Field(None, description="Filename of the LAMMPS input script (OutputReference)")
    slurm_file: Optional[Any] = Field(None, description="Filename of the SLURM run script (OutputReference)")
    job_id: Optional[Any] = Field(None, description="SLURM job ID for the LAMMPS run or 'local' (OutputReference)")
    restart_file: Optional[Any] = Field(None, description="Path to the restart.equil file generated by LAMMPS (OutputReference)")


class DmaxStructureEquilParserDocument(BaseModel):
    """Task document for parsing structure‑equilibration outputs."""

    restart_file: Optional[Any] = Field(None, description="Path to the restart.equil file used/retrieved")
    thermo_csv: Optional[str] = Field(None, description="Path to the CSV file containing thermo data")
    thermo_plot: Optional[str] = Field(None, description="Path to the time vs thermo plot")
    msd_plot: Optional[str] = Field(None, description="Path to the mean squared displacement plot")
    vacf_plot: Optional[str] = Field(None, description="Path to the velocity autocorrelation function plot")
    rdf_plot: Optional[str] = Field(None, description="Path to the radial distribution function plot")


# -----------------------------------------------------------------------------
# Updated DMA parser document
# -----------------------------------------------------------------------------

class DmaxDmaParserDocument(BaseModel):
    """Task document for parsing DMA outputs: moduli, phase, harmonics, and plots."""

    # --- analysis meta ---
    analysis_mode: str = Field(
        ..., description="Analysis method used: 'fft' (default) or 'fit'"
    )

    # --- primary mechanical properties ---
    storage_modulus: float = Field(..., description="Storage modulus G' in MPa")
    loss_modulus: float = Field(..., description="Loss modulus G'' in MPa")
    tan_delta: Optional[float] = Field(None, description="Loss tangent tan δ = G''/G'")
    elastic_modulus: float = Field(..., description="Elastic (Young) modulus from slope in MPa")
    poisson_ratio: float = Field(..., description="Poisson's ratio from lateral strain")

    # --- phase information ---
    phase_angle_rad: float = Field(..., description="Phase angle (radians)")
    phase_angle_deg: float = Field(..., description="Phase angle (degrees)")

    # --- harmonic / quality metrics (FFT mode) ---
    thd_pct: Optional[float] = Field(None, description="Total harmonic distortion (%) of pressure signal")
    snr_db: Optional[float] = Field(None, description="Signal‑to‑noise ratio of first harmonic (dB)")
    harmonic_magnitudes: Optional[Dict[int, float]] = Field(
        None,
        description="Relative magnitude |P_n|/|P_1| for n>1 (only present in FFT mode)",
    )

    # --- legacy fit diagnostics (fit mode) ---
    fit_r2: Optional[float] = Field(None, description="R² of sinusoidal fit (fit mode only)")
    fit_rmse: Optional[float] = Field(None, description="RMSE of sinusoidal fit in MPa (fit mode only)")
    amplitude: Optional[float] = Field(None, description="First‑harmonic pressure amplitude in MPa")

    # --- plot artefacts ---
    pressure_plot: str = Field(..., description="Path to pressure vs time plot with overlay")
    stress_strain_plot: str = Field(..., description="Path to stress–strain (Lissajous) plot")
    poisson_plot: Optional[str] = Field(None, description="Path to Poisson ratio vs strain/time plot")
    spectrum_plot: Optional[str] = Field(None, description="Path to magnitude‑spectrum (FFT) plot")


# -----------------------------------------------------------------------------
# The remaining Task / Flow documents remain unchanged
# -----------------------------------------------------------------------------

class DmaxDmaFlowDocument(BaseModel):
    """Flow document for a complete DMA run."""

    lammps_input: Optional[Any] = Field(None, description="Reference to DMA input task output")
    slurm_file: Optional[Any] = Field(None, description="SLURM script file (OutputReference)")
    job_id: Optional[Any] = Field(None, description="SLURM job ID or 'local' (OutputReference)")
    restart_file: Optional[Any] = Field(None, description="Restart file path (OutputReference)")
    parser_output: Optional[Any] = Field(None, description="Parsed DMA results (OutputReference)")


class DmaxStrainSizeConvergenceFlowDocument(BaseModel):
    """Document for strain‑size convergence analysis."""

    osc_amp_pc: List[float] = Field(..., description="Oscillation amplitudes tested (percent)")
    rmse: List[float] = Field(..., description="RMSE of sinusoidal fit for each amplitude")
    r2: List[float] = Field(..., description="R² of sinusoidal fit for each amplitude")
    plot: str = Field(..., description="Path to RMSE and R² vs amplitude plot")
    poisson: List[float] = Field(..., description="Poisson's ratio for each amplitude tested")
    poisson_plot: str = Field(..., description="Path to Poisson's ratio vs amplitude plot")
    optimal_osc_amp_pc: float = Field(..., description="Selected optimal oscillation amplitude (percent)")
    optimal_work_dir: str = Field(..., description="Working directory that produced the optimal run")
    optimal_restart_file: str = Field(..., description="Path to restart.equil of the optimal run")
    optimal_num_cycles: Any = Field(..., description="Minimum number of cycles for convergence")


class DmaxNumCyclesConvergenceFlowDocument(BaseModel):
    """Document for number‑of‑cycles convergence analysis."""

    num_cycles: List[int] = Field(..., description="List of cycle counts analyzed")
    tan_delta: List[float] = Field(..., description="List of tan δ values for each cycle count")
    threshold: float = Field(..., description="Relative convergence threshold used")
    optimal_num_cycles: int = Field(..., description="Minimum number of cycles for convergence")
    plot: str = Field(..., description="Path to tan δ vs number‑of‑cycles plot")


class DmaxErrorAnalysisFlowDocument(BaseModel):
    """Document for error analysis over frequencies."""

    freqs_ghz: List[float] = Field(..., description="Frequencies tested (GHz)")
    storage_mean: List[float] = Field(..., description="Mean storage modulus at each frequency (MPa)")
    storage_std: List[float] = Field(..., description="Std dev of storage modulus at each frequency (MPa)")
    loss_mean: List[float] = Field(..., description="Mean loss modulus at each frequency (MPa)")
    loss_std: List[float] = Field(..., description="Std dev of loss modulus at each frequency (MPa)")
    tan_mean: List[float] = Field(..., description="Mean tan δ at each frequency")
    tan_std: List[float] = Field(..., description="Std dev of tan δ at each frequency")
    storage_plot: str = Field(..., description="Path to storage modulus vs frequency plot")
    loss_plot: str = Field(..., description="Path to loss modulus vs frequency plot")
    tan_plot: str = Field(..., description="Path to tan δ vs frequency plot")


class DmaxGlassTransitionFlowDocument(BaseModel):
    """Document for glass‑transition temperature analysis."""

    temperatures: List[float] = Field(..., description="Temperatures tested (K)")
    storage_modulus: List[float] = Field(..., description="Storage modulus at each temperature (MPa)")
    loss_modulus: List[float] = Field(..., description="Loss modulus at each temperature (MPa)")
    tan_delta: List[float] = Field(..., description="Loss tangent at each temperature")
    glass_transition_temp: float = Field(..., description="Estimated glass transition temperature (K)")
    plot: str = Field(..., description="Plot of moduli and tan δ vs temperature with Tg annotation")
    data_csv: str = Field(..., description="CSV with moduli and Poisson ratio vs temperature")


class DmaxMasterCurveFlowDocument(BaseModel):
    """Document for master‑curve construction."""

    temperatures: List[float] = Field(..., description="Temperatures tested (K)")
    freqs_ghz: List[float] = Field(..., description="Frequencies tested (GHz)")
    data_csv: str = Field(..., description="CSV with all DMA metrics per temp and freq")
    master_plot_wlf1: str = Field(..., description="Master curve using WLF params (C1=17.44, C2=51.6)")
    master_plot_wlf2: str = Field(..., description="Master curve using WLF params (C1=8.86, C2=101.6)")
